apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo
  namespace: dev
spec:
  exporter:
    # endpoint: http://alloy.monitoring:4317
    endpoint: http://otlp-collector.opentelemetry-system:4318
    # endpoint: http://34.54.58.166/otlp
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: '1.0'
  env:
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    # - name: OTEL_METRICS_EXPORTER
    #   value: none
    - name: OTEL_INSTRUMENTATION_MICROMETER_ENABLED
      value: "true"
    - name: OTEL_METRIC_EXPORT_INTERVAL
      value: "15000"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_EXPORTER_OTLP_HEADERS
      value: Authorization=Basic Y2xpZW50OlRvb2tEZWVAODg=
